version: '3.7'
services:
  frontend:
    build:
      context: frontend/.
    hostname: frontend
    restart: always
    container_name: frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
    links:
      - backend
  backend:
    build:
      context: backend/.
    hostname: backend
    restart: always
    container_name: backend
    ports:
      - 7860:7860
    environment:
      - OPENAI_API_KEY=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
      - NEO4J_URL=neo4j://ec2-107-22-100-129.compute-1.amazonaws.com:7687/
      - NEO4J_USER=mingran
      - NEO4J_PASS=mingran123
      - MODEL_NAME=gpt-3.5-turbo      
    